Loan/Controllers/LoanController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Loan.Controllers
{
    public class LoanController : Controller
    {
        // GET: Loan
        [HttpGet]
        public ActionResult Index()
        {
            return View();
        }
        [HttpGet]
                public ActionResult Grades()
        {
            return View("Grades");
        }
        [HttpPost]
        public ActionResult Index(double balance, double IR, int year)
        {
            ViewBag.balance = balance;
            ViewBag.IR = IR;
            ViewBag.year = year;
            for (int i = 0; i < year; i++)
            {
                balance += balance * (IR / 100);
            }
            Double Total = balance;
            ViewBag.Total =Total;
            return View();
        }

        [HttpPost]
        public ActionResult Grades(FormCollection gradesForm)
        {
            double grade1 = Double.Parse(gradesForm["grade1"]);
            double grade2 = Double.Parse(gradesForm["grade2"]);
            double grade3 = Double.Parse(gradesForm["grade3"]);
            double avg = (grade1 + grade2 + grade3) / 3;
            String letter;
            if (avg <= 100 && avg >= 90)
            {
                letter = "A";
            }
            else if (avg <= 89 && avg >= 80)
            {
                letter = "B";
            }
            else if (avg <= 79 && avg >= 70)
            {
                letter = "C";
            }
            else if (avg <= 69 && avg >= 60)
            {
                letter = "D";
            }
            else
            {
                letter = "E";
            }

            ViewBag.grade = letter;
            return View("Grades");

        }
    }
}

Loan/Views/Loan/Grades.cshtml
@{
    ViewBag.Title = "Grades";
}

<h2>Grades</h2>
<form action="/Loan/Grades" method="post">
    <label>Grade 1:</label>
    <input type="number" name="grade1" min="0" max="100" required />
    <label>Grade 2:</label>
    <input type="number" name="grade2" min="0" max="100" required />
    <label>Grade 3:</label>
    <input type="number" name="grade3" min="0" max="100" required /><br />
    <input type="submit" value="Did you pass?" />
</form>

@if (ViewBag.grade != null)
{
    String grade = ViewBag.grade;
    if (grade == "A" || grade == "B")
    {
    <p> You did excellent! Good Job<h3 style="color:green">@grade</h3></p>
    }
    else if (grade == "C")
    {
        <p>You barely passed :D <h3 style="color:darkgoldenrod">@grade</h3></p>
    }
    else
    {
        <p>Ahhh you need to change programs <h3 style="color:red">@grade</h3></p>
    }
}
<br />Click here for @Html.ActionLink("Interest Rate Calculator", "Index", "Loan")

Loan/Views/Loan/Index.cshtml
@{
    ViewBag.Title = "Index";
}

<h2>Loan Calculator</h2>

<form action="/Loan/Index" method="post">
    Enter your Initial Investment Amount:
    <input type="number" name="balance" />

    Enter the Interest Rate:
    <input type="number" name="IR" />

    Number of Years:
    <input type="number" name="year" />
    <br /><br />
    <input type="Submit" value="Start Investing" />
</form>


@if (ViewBag.InVest != null || ViewBag.IR != null)
{
    <p>
        Given @ViewBag.Year years, an investment of $@ViewBag.balance, and an annual rate of %@ViewBag.IR, you will
        have $@ViewBag.Total
    </p>;

}

<br /> Click here for @Html.ActionLink("Grades Calculator", "Grades", "Loan")

Loan/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.8.3.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-3.3.1.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>